### ISSUE TITLE
Quick Feedback on MiniEx 7 by Winnie Soon 

### ISSUE THREAD

**Issue by siusoon** [PFisk/Mini-Exercises#8]
wowowwww you have positioned all the checkboxes manually! I like the way you try to observe objects properties, which one fits better for the tree trunk for example.

I would like to hear more from you about "The manipulation of HTML objects seems very forced compared to regular p5.js elements". DO you mean the HTML objects come with a lot of existing features that you think they are too complex and not easy to use?

**Comment by PFisk** [comment]
No. I like the existing features of the HTML objects, and in fact i would like to have more. What i mean is that it doesn't seem like the HTML objects are optimized for being used aesthetically, like we have done with this form art. It makes total sense though, as the indeed aren't made for this purpose. I ran in to a lot of problems, creating different shapes and forms with for loops and multidimensional arrays. I assumed that the errors i received was because of the HTML objects, as my code worked on regular elements in p5.js
